apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ei0a9mxep-nodejs
  janus-idp.io/tekton: ei0a9mxep-nodejs
  backstage.io/kubernetes-id: ei0a9mxep-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ei0a9mxep-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
