apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ei0a9mxep-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ei0a9mxep-nodejs 
  name: ei0a9mxep-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: ei0a9mxep-nodejs 
